### ISSUE TITLE
missing dependency

### ISSUE THREAD

**Issue by MursalRepo** [pykler/yajl-py#21]
Collecting yajl-py==2.1.2 (from -r requirements.txt (line 9))
  Downloading https://files.pythonhosted.org/packages/db/a8/01f4ef8eb17f04bef147b1be88975f86c845a78368c33f984e39f5cdaa37/yajl-py-2.1.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-42kb38vt/yajl-py/setup.py", line 4, in <module>
        from yajl import __version__ as version
      File "/tmp/pip-install-42kb38vt/yajl-py/yajl/__init__.py", line 18, in <module>
        from .yajl_parse import (
      File "/tmp/pip-install-42kb38vt/yajl-py/yajl/yajl_parse.py", line 6, in <module>
        import six
    ModuleNotFoundError: No module named 'six'

**Comment by ghost** [comment]
Can we get a new release of this made and pushed to PyPI so we can use this fix? It is very hard getting around this error and it was fixed a while back. Thanks.
