### ISSUE TITLE
Incompatible with anyjson

### ISSUE THREAD

**Issue by chrisspen** [pykler/yajl-py#5]
Yajl-py doesn't seem to expose the standard serialization methods, so installing it in a virtualenv that uses the anyjson throws the error:

```
File "/usr/local/lib/python2.7/dist-packages/anyjson/__init__.py", line 125, in <module>
     implementation = _JsonImplementation(modspec)
File "/usr/local/lib/python2.7/dist-packages/anyjson/__init__.py", line 60, in __init__
     self._encode = getattr(module, modinfo["encoder"])
AttributeError: 'module' object has no attribute 'dumps'
```

I'm not sure if this is an issue with yajl-py or anyjson, but I thought I'd mention it. Would it be possible to expose load/loads/dump/dumps methods so it's interchangeable with other JSON packages?

**Comment by sunyoubo** [comment]
I met the same problem , use celery: from celery.decorators import task

**Comment by sunyoubo** [comment]
File "locationtask.py", line 15, in <module>
    from celery.decorators import task
  File "/usr/local/lib/python2.6/dist-packages/celery-2.2.5-py2.6.egg/celery/decorators.py", line 17, in <module>
    from celery import task as _task
  File "/usr/local/lib/python2.6/dist-packages/celery-2.2.5-py2.6.egg/celery/task/__init__.py", line 5, in <module>
    from celery.task.base import Task, PeriodicTask
  File "/usr/local/lib/python2.6/dist-packages/celery-2.2.5-py2.6.egg/celery/task/base.py", line 719, in <module>
    Task = current_app.Task
  File "/usr/local/lib/python2.6/dist-packages/celery-2.2.5-py2.6.egg/celery/local.py", line 56, in __getattr__
    return getattr(self._get_current_object(), name)
  File "/usr/local/lib/python2.6/dist-packages/kombu-1.5.1-py2.6.egg/kombu/utils/__init__.py", line 269, in __get__
    value = obj.__dict__[self.__name__] = self.__get(obj)
  File "/usr/local/lib/python2.6/dist-packages/celery-2.2.5-py2.6.egg/celery/app/__init__.py", line 163, in Task
    return self.create_task_cls()
  File "/usr/local/lib/python2.6/dist-packages/celery-2.2.5-py2.6.egg/celery/app/__init__.py", line 57, in create_task_cls
    conf = self.conf
  File "/usr/local/lib/python2.6/dist-packages/kombu-1.5.1-py2.6.egg/kombu/utils/__init__.py", line 269, in __get__
    value = obj.__dict__[self.__name__] = self.__get(obj)
  File "/usr/local/lib/python2.6/dist-packages/celery-2.2.5-py2.6.egg/celery/app/base.py", line 317, in conf
    return self._get_config()
  File "/usr/local/lib/python2.6/dist-packages/celery-2.2.5-py2.6.egg/celery/app/base.py", line 301, in _get_config
    [self.prepare_config(self.loader.conf), deepcopy(DEFAULTS)])
  File "/usr/local/lib/python2.6/dist-packages/kombu-1.5.1-py2.6.egg/kombu/utils/__init__.py", line 269, in __get__
    value = obj.__dict__[self.__name__] = self.__get(obj)
  File "/usr/local/lib/python2.6/dist-packages/celery-2.2.5-py2.6.egg/celery/app/base.py", line 334, in loader
    return get_loader_cls(self.loader_cls)(app=self)
  File "/usr/local/lib/python2.6/dist-packages/celery-2.2.5-py2.6.egg/celery/loaders/__init__.py", line 14, in get_loader_cls
    return get_cls_by_name(loader, LOADER_ALIASES)
  File "/usr/local/lib/python2.6/dist-packages/celery-2.2.5-py2.6.egg/celery/utils/__init__.py", line 311, in get_cls_by_name
    module = imp(module_name)
  File "/usr/local/lib/python2.6/dist-packages/importlib-1.0.2-py2.6.egg/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/local/lib/python2.6/dist-packages/celery-2.2.5-py2.6.egg/celery/loaders/default.py", line 6, in <module>
    from celery.loaders.base import BaseLoader
  File "/usr/local/lib/python2.6/dist-packages/celery-2.2.5-py2.6.egg/celery/loaders/base.py", line 6, in <module>
    from anyjson import deserialize
  File "/usr/local/lib/python2.6/dist-packages/anyjson-0.3.3-py2.6.egg/anyjson/__init__.py", line 125, in <module>
    implementation = _JsonImplementation(modspec)
  File "/usr/local/lib/python2.6/dist-packages/anyjson-0.3.3-py2.6.egg/anyjson/__init__.py", line 60, in __init__
    self._encode = getattr(module, modinfo["encoder"])
AttributeError: 'module' object has no attribute 'dumps'

**Comment by pykler** [comment]
Works for me, can you tell me what version of yajl-py you have installed?

**Comment by sunyoubo** [comment]
sorry,  I  haven‘t package yajl-py, What is this packet function?

**Comment by pykler** [comment]
Try this in a python shell:

```python
import yajl
print yajl.__version__
```

What do you get?

**Comment by sunyoubo** [comment]
>>> import yajl
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named yajl
thanks, I never install yajl module

**Comment by pykler** [comment]
So not sure what ur problem would be

**Comment by sunyoubo** [comment]
ok, thanks
